import { StyleSheet } from 'react-native';

export const shopItemStyle = (x, y) =>
  StyleSheet.create({
    width: 60,
    height: 40,
    marginBottom: 20,
    position: 'absolute',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
    top: x,
    left: y,
  });

export const appStyle = StyleSheet.create({
  scoreText: {
    fontFamily: 'AbrilFatface-Regular',
    fontSize: 30,
    color: 'white',
    position: 'absolute',
    top: -60,
    right: '5%',
  },
  heartButton: {
    width: 80,
    height: 50,
    position: 'absolute',
    top: '2%',
    left: '5%',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  heartImage: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
  item4Image: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
    position: 'absolute',
    top: '0%',
    right: '0%',
  },
  leftBottomView: {
    width: '50%',
    height: '100%',
  },
  bottomView: {
    width: '100%',
    height: 450,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  item2Image: {
    width: 150,
    height: 150,
    resizeMode: 'contain',
    position: 'absolute',
    top: '30%',
    right: '0%',
  },
  item3Image: {
    width: 120,
    height: 120,
    resizeMode: 'contain',
    position: 'absolute',
    top: '0%',
    left: '0%',
  },
  item5Image: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
    position: 'absolute',
    bottom: '0%',
    left: '0%',
  },
  item1Image: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
    position: 'absolute',
    bottom: '20%',
    left: '0%',
  },
  itemText: {
    fontFamily: 'AbrilFatface-Regular',
    fontSize: 16,
    color: 'white',
  },
  rightBottomView: {
    width: '50%',
    height: '100%',
    alignItems: 'center',
  },
  frameImage: {
    width: 158,
    height: 411,
    resizeMode: 'contain',
  },
  priceText: {
    fontFamily: 'AbrilFatface-Regular',
    fontSize: 18,
    color: 'white',
  },
  turnText: {
    fontFamily: 'AbrilFatface-Regular',
    fontSize: 30,
    color: 'white',
  },
  shopItemImage: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  timeView: {
    width: '30%',
    height: 50,
    paddingHorizontal: 20,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timeLabelText: {
    fontFamily: 'AbrilFatface-Regular',
    fontSize: 30,
    color: 'black',
  },
  timeText: {
    fontFamily: 'AbrilFatface-Regular',
    fontSize: 50,
    paddingVertical: 40,
    color: 'white',
  },
  answerView: {
    width: '100%',
    height: 250,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  answerABView: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 80,
  },
  answerButton: {
    width: 150,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    backgroundColor: '#cbcbcb',
    borderColor: 'white',
  },
  winImage: {
    width: 250,
    height: 350,
    position: 'absolute',
    top: 0,
    resizeMode: 'contain',
  },
  scoreWin: {
    fontFamily: 'AbrilFatface-Regular',
    fontSize: 90,
    color: 'red',
  },
  scoreView: {
    width: 200,
    height: 150,
    position: 'absolute',
    top: '40%',
    left: '10%',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'column',
  },
  priceShopItemsImage: {
    width: 250,
    height: 200,
    resizeMode: 'contain',
  },
  OKImage: {
    width: 80,
    height: 80,
    resizeMode: 'contain',
  },
  itemView: {
    width: 150,
    height: 27,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemMenuText: {
    width: 130,
    height: '100%',
    alignItems: 'center',
    flexDirection: 'row',
  },
  backText: {
    position: 'absolute',
    paddingTop: 20,
    left: '5%',
    fontFamily: 'AbrilFatface-Regular',
    fontSize: 30,
    color: 'white',
  },
  menuText: {
    fontSize: 50,
    width: '60%',
    textAlign: 'center',
    fontFamily: 'AbrilFatface-Regular',
    color: 'white',
  },
  labelText: {
    fontSize: 40,
    width: '100%',
    textAlign: 'center',
    fontFamily: 'AbrilFatface-Regular',
    color: 'white',
  },
  homeView: {
    marginTop: 80,
    width: '100%',
    height: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  resultView: {
    width: '70%',
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultImage: {
    width: 300,
    height: 200,
    resizeMode: 'contain',
  },
  shopImgae: {
    width: 340,
    height: 400,
    resizeMode: 'cover',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stateResult: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    position: 'absolute',
    top: '0%',
    right: '8%',
    zIndex: 3,
  },
  playImage: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
    position: 'absolute',
    bottom: -75,
    right: '-25%',
  },
});

export const musicsStyle = StyleSheet.create({
  musicWrapper: {
    position: 'absolute',
    alignSelf: 'center',
    bottom: '50%',
  },
  musicButton: {
    padding: 10,
    backgroundColor: 'gray',
  },
  musicButtonTitle: {
    color: 'green',
  },
});

export const layoutStyle = StyleSheet.create({
  background: {
    resizeMode: 'contain',
    width: '100%',
    height: '100%',
  },
  land: {
    resizeMode: 'cover',
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    height: '40%',
  },
  children: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 3,
    elevation: 3,
  },
});

export const paymentStyle = StyleSheet.create({
  center: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
});

export const buttonStyle = StyleSheet.create({
  buttons: {
    padding: 10,
    paddingTop: 30,
    top: '10%',
    zIndex: 3,
    elevation: 3,
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  button: {
    width: 150,
    height: 50,
    marginLeft: 20,
    marginBottom: 40,
    textAlign: 'center',
    padding: 5,
  },
  text: {
    color: 'white',
    textAlign: 'center',
    fontSize: 18,
    fontFamily: 'AbrilFatface-Regular',
  },
  textSmall: {
    color: 'white',
    textAlign: 'center',
    fontSize: 14,
  },
});
